In [117]:
pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\musta\miniconda3\envs\minimal_ds\lib\site-packages (16.1.0)
Requirement already satisfied: numpy>=1.16.6 in c:\users\musta\miniconda3\envs\minimal_ds\lib\site-packages (from pyarrow) (1.26.4)
Note: you may need to restart the kernel to use updated packages.

In [118]:
import pandas as pd
import pyarrow
import sys
print(sys.version)
print('pandas version', pd.__version__)

3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)]
pandas version 2.2.2

# I/O (Reading and Writing)

In [119]:
# Example with creating own data
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': ['23', '30', '35'],
    'City':['New York', 'Paris', 'London']
}

df = pd.DataFrame(data)
data

{'Name': ['Alice', 'Bob', 'Charlie'],
 'Age': ['23', '30', '35'],
 'City': ['New York', 'Paris', 'London']}

In [120]:
df

      Name Age      City
0    Alice  23  New York
1      Bob  30     Paris
2  Charlie  35    London

In [121]:
# Pandas has many read methods pd.read_{file_4ype}(file_name)

In [122]:
df = pd.read_parquet('Combined_Flights_2020.parquet', engine='pyarrow')

In [123]:
df

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2020-09-01,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2034.0,0.0,76.0,111.0,96.0,477.0,2020,3,9,1,2,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N506AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2030.0,4.0,2056,-22.0,0.0,-2.0,2000-2059,2,0.0
1,2020-09-02,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2027.0,0.0,68.0,111.0,89.0,477.0,2020,3,9,2,3,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N512AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2022.0,5.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0
2,2020-09-03,Comair Inc.,PHL,DAY,False,False,1905,1855.0,0.0,-10.0,2122.0,26.0,77.0,111.0,147.0,477.0,2020,3,9,3,4,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N710PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,65.0,2000.0,2117.0,5.0,2056,26.0,1.0,1.0,2000-2059,2,0.0
3,2020-09-04,Comair Inc.,PHL,DAY,False,False,1905,1857.0,0.0,-8.0,2027.0,0.0,73.0,111.0,90.0,477.0,2020,3,9,4,5,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N712PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,13.0,1910.0,2023.0,4.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0
4,2020-09-05,Comair Inc.,PHL,DAY,False,False,1905,1856.0,0.0,-9.0,2026.0,0.0,72.0,111.0,90.0,477.0,2020,3,9,5,6,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N705PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,14.0,1910.0,2022.0,4.0,2056,-30.0,0.0,-2.0,2000-2059,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331233,2020-04-01,Republic Airlines,CLT,DEN,True,False,1645,NaN,NaN,NaN,NaN,NaN,NaN,235.0,NaN,1337.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3404,YX,20452,YX,N648RW,3404,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,NaN,NaN,1600-1659,NaN,NaN,NaN,NaN,1840,NaN,NaN,NaN,1800-1859,6,0.0
331234,2020-04-01,Republic Airlines,CLE,EWR,False,False,1700,1652.0,0.0,-8.0,1812.0,0.0,61.0,107.0,80.0,404.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3403,YX,20452,YX,N645RW,3403,11042,1104205,30647,"Cleveland, OH",OH,39,Ohio,44,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,0.0,-1.0,1700-1759,13.0,1705.0,1806.0,6.0,1847,-35.0,0.0,-2.0,1800-1859,2,0.0
331235,2020-04-01,Republic Airlines,BUF,EWR,False,False,700,933.0,153.0,153.0,1040.0,132.0,55.0,88.0,67.0,282.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3402,YX,20452,YX,N725YX,3402,10792,1079206,30792,"Buffalo, NY",NY,36,New York,22,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,10.0,0700-0759,8.0,941.0,1036.0,4.0,828,132.0,1.0,8.0,0800-0859,2,0.0
331236,2020-04-01,Republic Airlines,HRL,IAH,False,False,730,720.0,0.0,-10.0,831.0,0.0,52.0,78.0,71.0,295.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3401,YX,20452,YX,N730YX,3401,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,11.0,731.0,823.0,8.0,848,-17.0,0.0,-2.0,0800-0859,2,0.0
331237,2020-04-01,Republic Airlines,DCA,ORD,False,False,845,837.0,0.0,-8.0,930.0,0.0,96.0,132.0,113.0,612.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3400,YX,20452,YX,N861RW,3400,11278,1127805,30852,"Washington, DC",VA,51,Virginia,38,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,0800-0859,10.0,847.0,923.0,7.0,957,-27.0,0.0,-2.0,0900-0959,3,0.0

In [124]:
# Writing to DB use pd.to_{file_type}(file_name, index=False)

# DataFrame Basics

In [125]:
df.head() # by default, lets you see first 5 rows, may hide middle columns
# use to displpay more columns
pd.set_option('display.max_columns', 500)

In [126]:
df.head(7) # or add a number in brackets

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2020-09-01,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2034.0,0.0,76.0,111.0,96.0,477.0,2020,3,9,1,2,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N506AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2030.0,4.0,2056,-22.0,0.0,-2.0,2000-2059,2,0.0
1,2020-09-02,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2027.0,0.0,68.0,111.0,89.0,477.0,2020,3,9,2,3,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N512AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2022.0,5.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0
2,2020-09-03,Comair Inc.,PHL,DAY,False,False,1905,1855.0,0.0,-10.0,2122.0,26.0,77.0,111.0,147.0,477.0,2020,3,9,3,4,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N710PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,65.0,2000.0,2117.0,5.0,2056,26.0,1.0,1.0,2000-2059,2,0.0
3,2020-09-04,Comair Inc.,PHL,DAY,False,False,1905,1857.0,0.0,-8.0,2027.0,0.0,73.0,111.0,90.0,477.0,2020,3,9,4,5,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N712PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,13.0,1910.0,2023.0,4.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0
4,2020-09-05,Comair Inc.,PHL,DAY,False,False,1905,1856.0,0.0,-9.0,2026.0,0.0,72.0,111.0,90.0,477.0,2020,3,9,5,6,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N705PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,14.0,1910.0,2022.0,4.0,2056,-30.0,0.0,-2.0,2000-2059,2,0.0
5,2020-09-06,Comair Inc.,PHL,DAY,False,False,1905,1853.0,0.0,-12.0,2023.0,0.0,70.0,111.0,90.0,477.0,2020,3,9,6,7,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N710PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,13.0,1906.0,2016.0,7.0,2056,-33.0,0.0,-2.0,2000-2059,2,0.0
6,2020-09-07,Comair Inc.,PHL,DAY,False,False,1905,1901.0,0.0,-4.0,2038.0,0.0,76.0,111.0,97.0,477.0,2020,3,9,7,1,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N543EA,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,14.0,1915.0,2031.0,7.0,2056,-18.0,0.0,-2.0,2000-2059,2,0.0

In [127]:
df.tail() # shows 5 last rows, or number specified

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
331233,2020-04-01,Republic Airlines,CLT,DEN,True,False,1645,NaN,NaN,NaN,NaN,NaN,NaN,235.0,NaN,1337.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3404,YX,20452,YX,N648RW,3404,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,NaN,NaN,1600-1659,NaN,NaN,NaN,NaN,1840,NaN,NaN,NaN,1800-1859,6,0.0
331234,2020-04-01,Republic Airlines,CLE,EWR,False,False,1700,1652.0,0.0,-8.0,1812.0,0.0,61.0,107.0,80.0,404.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3403,YX,20452,YX,N645RW,3403,11042,1104205,30647,"Cleveland, OH",OH,39,Ohio,44,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,0.0,-1.0,1700-1759,13.0,1705.0,1806.0,6.0,1847,-35.0,0.0,-2.0,1800-1859,2,0.0
331235,2020-04-01,Republic Airlines,BUF,EWR,False,False,700,933.0,153.0,153.0,1040.0,132.0,55.0,88.0,67.0,282.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3402,YX,20452,YX,N725YX,3402,10792,1079206,30792,"Buffalo, NY",NY,36,New York,22,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,10.0,0700-0759,8.0,941.0,1036.0,4.0,828,132.0,1.0,8.0,0800-0859,2,0.0
331236,2020-04-01,Republic Airlines,HRL,IAH,False,False,730,720.0,0.0,-10.0,831.0,0.0,52.0,78.0,71.0,295.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3401,YX,20452,YX,N730YX,3401,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,11.0,731.0,823.0,8.0,848,-17.0,0.0,-2.0,0800-0859,2,0.0
331237,2020-04-01,Republic Airlines,DCA,ORD,False,False,845,837.0,0.0,-8.0,930.0,0.0,96.0,132.0,113.0,612.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3400,YX,20452,YX,N861RW,3400,11278,1127805,30852,"Washington, DC",VA,51,Virginia,38,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,0800-0859,10.0,847.0,923.0,7.0,957,-27.0,0.0,-2.0,0900-0959,3,0.0

In [128]:
df.sample(10) # random subset of row, or specified number

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
48693,2020-06-16,SkyWest Airlines Inc.,CID,DFW,False,False,1317,1309.0,0.0,-8.0,1504.0,0.0,95.0,124.0,115.0,685.0,2020,2,6,16,2,AA,AA_CODESHARE,19805,AA,2961,OO,20304,OO,N752EV,2961,11003,1100303,31003,"Cedar Rapids/Iowa City, IA",IA,19,Iowa,61,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,0.0,-1.0,1300-1359,12.0,1321.0,1456.0,8.0,1521,-17.0,0.0,-2.0,1500-1559,3,0.0
225914,2020-11-03,Endeavor Air Inc.,MSP,ICT,False,False,1250,1248.0,0.0,-2.0,1414.0,0.0,72.0,112.0,86.0,545.0,2020,4,11,3,2,DL,DL_CODESHARE,19790,DL,4874,9E,20363,9E,N292PQ,4874,13487,1348702,31650,"Minneapolis, MN",MN,27,Minnesota,63,12278,1227805,30928,"Wichita, KS",KS,20,Kansas,62,0.0,-1.0,1200-1259,9.0,1257.0,1409.0,5.0,1442,-28.0,0.0,-2.0,1400-1459,3,0.0
76061,2020-04-02,SkyWest Airlines Inc.,BOI,ORD,False,False,830,823.0,0.0,-7.0,1248.0,0.0,182.0,219.0,205.0,1437.0,2020,2,4,2,4,UA,UA_CODESHARE,19977,UA,5401,OO,20304,OO,N148SY,5401,10713,1071302,30713,"Boise, ID",ID,16,Idaho,83,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,0800-0859,18.0,841.0,1243.0,5.0,1309,-21.0,0.0,-2.0,1300-1359,6,0.0
238972,2020-12-14,Mesa Airlines Inc.,DFW,MFE,False,False,1905,2017.0,72.0,72.0,2144.0,52.0,71.0,107.0,87.0,469.0,2020,4,12,14,1,AA,AA_CODESHARE,19805,AA,5762,YV,20378,YV,N907FJ,5762,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,13256,1325602,33256,"Mission/McAllen/Edinburg, TX",TX,48,Texas,74,1.0,4.0,1900-1959,11.0,2028.0,2139.0,5.0,2052,52.0,1.0,3.0,2000-2059,2,0.0
375670,2020-03-25,Comair Inc.,BDL,DCA,False,False,534,522.0,0.0,-12.0,649.0,0.0,71.0,85.0,87.0,313.0,2020,1,3,25,3,AA,AA_CODESHARE,19805,AA,5427,OH,20397,OH,N220PS,5427,10529,1052906,30529,"Hartford, CT",CT,9,Connecticut,11,11278,1127805,30852,"Washington, DC",VA,51,Virginia,38,0.0,-1.0,0001-0559,11.0,533.0,644.0,5.0,659,-10.0,0.0,-1.0,0600-0659,2,0.0
83532,2020-01-06,Capital Cargo International,CAE,PHL,False,False,1245,1242.0,0.0,-3.0,1419.0,0.0,77.0,99.0,97.0,523.0,2020,1,1,6,1,AA,AA_CODESHARE,19805,AA,4998,PT,20427,PT,N692AE,4998,10868,1086803,30868,"Columbia, SC",SC,45,South Carolina,37,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,0.0,-1.0,1200-1259,14.0,1256.0,1413.0,6.0,1424,-5.0,0.0,-1.0,1400-1459,3,0.0
295452,2020-02-16,Endeavor Air Inc.,ORF,JFK,False,False,1142,1135.0,0.0,-7.0,1240.0,0.0,44.0,88.0,65.0,290.0,2020,1,2,16,7,DL,DL_CODESHARE,19790,DL,4829,9E,20363,9E,N8976E,4829,13931,1393102,33667,"Norfolk, VA",VA,51,Virginia,38,12478,1247805,31703,"New York, NY",NY,36,New York,22,0.0,-1.0,1100-1159,12.0,1147.0,1231.0,9.0,1310,-30.0,0.0,-2.0,1300-1359,2,0.0
239547,2020-03-27,Southwest Airlines Co.,MDW,CMH,False,False,1515,1513.0,0.0,-2.0,1708.0,0.0,43.0,75.0,55.0,283.0,2020,1,3,27,5,WN,WN,19393,WN,626,WN,19393,WN,N967WN,626,13232,1323202,30977,"Chicago, IL",IL,17,Illinois,41,11066,1106606,31066,"Columbus, OH",OH,39,Ohio,44,0.0,-1.0,1500-1559,9.0,1522.0,1705.0,3.0,1730,-22.0,0.0,-2.0,1700-1759,2,0.0
225,2020-07-22,Southwest Airlines Co.,CLE,MDW,False,False,1730,1722.0,0.0,-8.0,1721.0,0.0,49.0,80.0,59.0,307.0,2020,3,7,22,3,WN,WN,19393,WN,1541,WN,19393,WN,N755SA,1541,11042,1104205,30647,"Cleveland, OH",OH,39,Ohio,44,13232,1323202,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,1700-1759,5.0,1727.0,1716.0,5.0,1750,-29.0,0.0,-2.0,1700-1759,2,0.0
100341,2020-01-20,Spirit Air Lines,TPA,ATL,False,False,1127,1131.0,4.0,4.0,1303.0,0.0,69.0,102.0,92.0,406.0,2020,1,1,20,1,NK,NK,20416,NK,762,NK,20416,NK,N656NK,762,15304,1530402,33195,"Tampa, FL",FL,12,Florida,33,10397,1039707,30397,"Atlanta, GA",GA,13,Georgia,34,0.0,0.0,1100-1159,14.0,1145.0,1254.0,9.0,1309,-6.0,0.0,-1.0,1300-1359,2,0.0

In [129]:
df.columns # shows column names

Index(['FlightDate', 'Airline', 'Origin', 'Dest', 'Cancelled', 'Diverted',
       'CRSDepTime', 'DepTime', 'DepDelayMinutes', 'DepDelay', 'ArrTime',
       'ArrDelayMinutes', 'AirTime', 'CRSElapsedTime', 'ActualElapsedTime',
       'Distance', 'Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek',
       'Marketing_Airline_Network', 'Operated_or_Branded_Code_Share_Partners',
       'DOT_ID_Marketing_Airline', 'IATA_Code_Marketing_Airline',
       'Flight_Number_Marketing_Airline', 'Operating_Airline',
       'DOT_ID_Operating_Airline', 'IATA_Code_Operating_Airline',
       'Tail_Number', 'Flight_Number_Operating_Airline', 'OriginAirportID',
       'OriginAirportSeqID', 'OriginCityMarketID', 'OriginCityName',
       'OriginState', 'OriginStateFips', 'OriginStateName', 'OriginWac',
       'DestAirportID', 'DestAirportSeqID', 'DestCityMarketID', 'DestCityName',
       'DestState', 'DestStateFips', 'DestStateName', 'DestWac', 'DepDel15',
       'DepartureDelayGroups', 'DepTimeBlk', 'TaxiOut', 'WheelsOff',
       'WheelsOn', 'TaxiIn', 'CRSArrTime', 'ArrDelay', 'ArrDel15',
       'ArrivalDelayGroups', 'ArrTimeBlk', 'DistanceGroup',
       'DivAirportLandings'],
      dtype='object')

In [130]:
df.index # shows index values, here start at 0, ends at 1571, increments by 1

Index([     0,      1,      2,      3,      4,      5,      6,      7,      8,
            9,
       ...
       331228, 331229, 331230, 331231, 331232, 331233, 331234, 331235, 331236,
       331237],
      dtype='int64', length=5022397)

In [131]:
df.info() # info abt dataframe, size, column name, count, type and file size
print()
df.info(verbose=False) # Less detailed

<class 'pandas.core.frame.DataFrame'>
Index: 5022397 entries, 0 to 331237
Data columns (total 61 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   FlightDate                               datetime64[us]
 1   Airline                                  object
 2   Origin                                   object
 3   Dest                                     object
 4   Cancelled                                bool
 5   Diverted                                 bool
 6   CRSDepTime                               int64
 7   DepTime                                  float64
 8   DepDelayMinutes                          float64
 9   DepDelay                                 float64
 10  ArrTime                                  float64
 11  ArrDelayMinutes                          float64
 12  AirTime                                  float64
 13  CRSElapsedTime                           float64
 14  ActualElapsedTime                        float64
 15  Distance                                 float64
 16  Year                                     int64
 17  Quarter                                  int64
 18  Month                                    int64
 19  DayofMonth                               int64
 20  DayOfWeek                                int64
 21  Marketing_Airline_Network                object
 22  Operated_or_Branded_Code_Share_Partners  object
 23  DOT_ID_Marketing_Airline                 int64
 24  IATA_Code_Marketing_Airline              object
 25  Flight_Number_Marketing_Airline          int64
 26  Operating_Airline                        object
 27  DOT_ID_Operating_Airline                 int64
 28  IATA_Code_Operating_Airline              object
 29  Tail_Number                              object
 30  Flight_Number_Operating_Airline          int64
 31  OriginAirportID                          int64
 32  OriginAirportSeqID                       int64
 33  OriginCityMarketID                       int64
 34  OriginCityName                           object
 35  OriginState                              object
 36  OriginStateFips                          int64
 37  OriginStateName                          object
 38  OriginWac                                int64
 39  DestAirportID                            int64
 40  DestAirportSeqID                         int64
 41  DestCityMarketID                         int64
 42  DestCityName                             object
 43  DestState                                object
 44  DestStateFips                            int64
 45  DestStateName                            object
 46  DestWac                                  int64
 47  DepDel15                                 float64
 48  DepartureDelayGroups                     float64
 49  DepTimeBlk                               object
 50  TaxiOut                                  float64
 51  WheelsOff                                float64
 52  WheelsOn                                 float64
 53  TaxiIn                                   float64
 54  CRSArrTime                               int64
 55  ArrDelay                                 float64
 56  ArrDel15                                 float64
 57  ArrivalDelayGroups                       float64
 58  ArrTimeBlk                               object
 59  DistanceGroup                            int64
 60  DivAirportLandings                       float64
dtypes: bool(2), datetime64[us](1), float64(19), int64(22), object(17)
memory usage: 2.3+ GB

<class 'pandas.core.frame.DataFrame'>
Index: 5022397 entries, 0 to 331237
Columns: 61 entries, FlightDate to DivAirportLandings
dtypes: bool(2), datetime64[us](1), float64(19), int64(22), object(17)
memory usage: 2.3+ GB

In [132]:
df.describe() # Descritpive stats of data

,FlightDate,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,DOT_ID_Marketing_Airline,Flight_Number_Marketing_Airline,DOT_ID_Operating_Airline,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginStateFips,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestStateFips,DestWac,DepDel15,DepartureDelayGroups,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,DistanceGroup,DivAirportLandings
count,5022397,5.022397e+06,4.722777e+06,4.722714e+06,4.722714e+06,4.720398e+06,4.712930e+06,4.712930e+06,5.022392e+06,4.712930e+06,5.022397e+06,5022397.0,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,5.022397e+06,4.722714e+06,4.722714e+06,4.721971e+06,4.721971e+06,4.720397e+06,4.720397e+06,5.022397e+06,4.712930e+06,4.712930e+06,4.712930e+06,5.022397e+06,5.022310e+06
mean,2020-06-11 12:26:35.288944,1.315357e+03,1.312706e+03,6.761073e+00,2.064780e+00,1.480714e+03,6.951154e+00,1.061841e+02,1.351304e+02,1.283775e+02,7.546099e+02,2020.0,2.289412e+00,5.857175e+00,1.573752e+01,3.996955e+00,1.981555e+04,2.690128e+03,1.999914e+04,2.690056e+03,1.266246e+04,1.266250e+06,3.174615e+04,2.748132e+01,5.543480e+01,1.266249e+04,1.266253e+06,3.174623e+04,2.748179e+01,5.543601e+01,9.174301e-02,-4.660689e-01,1.536379e+01,1.337111e+03,1.473272e+03,6.835988e+00,1.494236e+03,-4.863644e+00,9.950392e-02,-7.889990e-01,3.496368e+00,2.814243e-03
min,2020-01-01 00:00:00,1.000000e+00,1.000000e+00,0.000000e+00,-1.310000e+02,1.000000e+00,0.000000e+00,7.000000e+00,-7.700000e+01,1.300000e+01,2.900000e+01,2020.0,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.939300e+04,1.000000e+00,1.939300e+04,1.000000e+00,1.013500e+04,1.013506e+06,3.007000e+04,1.000000e+00,1.000000e+00,1.013500e+04,1.013506e+06,3.007000e+04,1.000000e+00,1.000000e+00,0.000000e+00,-2.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,-1.390000e+02,0.000000e+00,-2.000000e+00,1.000000e+00,0.000000e+00
25%,2020-02-28 00:00:00,9.250000e+02,9.240000e+02,0.000000e+00,-7.000000e+00,1.115000e+03,0.000000e+00,5.800000e+01,8.600000e+01,8.000000e+01,3.500000e+02,2020.0,1.000000e+00,2.000000e+00,8.000000e+00,2.000000e+00,1.979000e+04,1.083000e+03,1.979000e+04,1.083000e+03,1.129200e+04,1.129202e+06,3.063100e+04,1.200000e+01,3.400000e+01,1.129200e+04,1.129202e+06,3.063100e+04,1.200000e+01,3.400000e+01,0.000000e+00,-1.000000e+00,1.000000e+01,9.400000e+02,1.110000e+03,4.000000e+00,1.123000e+03,-1.900000e+01,0.000000e+00,-2.000000e+00,2.000000e+00,0.000000e+00
50%,2020-06-01 00:00:00,1.312000e+03,1.313000e+03,0.000000e+00,-4.000000e+00,1.510000e+03,0.000000e+00,8.900000e+01,1.190000e+02,1.120000e+02,6.100000e+02,2020.0,2.000000e+00,6.000000e+00,1.600000e+01,4.000000e+00,1.980500e+04,2.299000e+03,1.997700e+04,2.299000e+03,1.288900e+04,1.288903e+06,3.145300e+04,2.600000e+01,5.100000e+01,1.288900e+04,1.288903e+06,3.145300e+04,2.600000e+01,5.100000e+01,0.000000e+00,-1.000000e+00,1.300000e+01,1.326000e+03,1.504000e+03,5.000000e+00,1.516000e+03,-1.100000e+01,0.000000e+00,-1.000000e+00,3.000000e+00,0.000000e+00
75%,2020-09-22 00:00:00,1.710000e+03,1.712000e+03,0.000000e+00,-1.000000e+00,1.855000e+03,0.000000e+00,1.360000e+02,1.650000e+02,1.580000e+02,9.920000e+02,2020.0,3.000000e+00,9.000000e+00,2.300000e+01,6.000000e+00,1.997700e+04,4.289000e+03,2.037800e+04,4.289000e+03,1.405700e+04,1.405702e+06,3.257500e+04,4.200000e+01,8.200000e+01,1.405700e+04,1.405702e+06,3.257500e+04,4.200000e+01,8.200000e+01,0.000000e+00,-1.000000e+00,1.800000e+01,1.726000e+03,1.849000e+03,8.000000e+00,1.901000e+03,-1.000000e+00,0.000000e+00,-1.000000e+00,4.000000e+00,0.000000e+00
max,2020-12-31 00:00:00,2.359000e+03,2.400000e+03,3.890000e+03,3.890000e+03,2.400000e+03,3.864000e+03,6.980000e+02,7.000000e+02,7.630000e+02,5.095000e+03,2020.0,4.000000e+00,1.200000e+01,3.100000e+01,7.000000e+00,2.043600e+04,9.888000e+03,2.116700e+04,9.888000e+03,1.686900e+04,1.686901e+06,3.610100e+04,7.800000e+01,9.300000e+01,1.686900e+04,1.686901e+06,3.610100e+04,7.800000e+01,9.300000e+01,1.000000e+00,1.200000e+01,1.890000e+02,2.400000e+03,2.400000e+03,2.910000e+02,2.400000e+03,3.864000e+03,1.000000e+00,1.200000e+01,1.100000e+01,9.000000e+00
std,NaN,4.615186e+02,4.669689e+02,3.526909e+01,3.639112e+01,4.830386e+02,3.469173e+01,6.592856e+01,6.729927e+01,6.713504e+01,5.504107e+02,0.0,1.207801e+00,3.715543e+00,8.811530e+00,2.003575e+00,2.694407e+02,1.834531e+03,3.901717e+02,1.834477e+03,1.541555e+03,1.541553e+05,1.345228e+03,1.670100e+01,2.595192e+01,1.541572e+03,1.541569e+05,1.345237e+03,1.670102e+01,2.595217e+01,2.886629e-01,1.620081e+00,8.335184e+00,4.667863e+02,4.810762e+02,5.080012e+00,4.791379e+02,3.842280e+01,2.993374e-01,1.772376e+00,2.180196e+00,1.088503e-01

In [133]:
df[['Airline']].describe() # can be run on non numeric columns

                       Airline
count                  5022397
unique                      25
top     Southwest Airlines Co.
freq                    961276

In [134]:
df.shape # rows, columns

(5022397, 61)

In [135]:
len(df) # number of rows

5022397

# Subsetting DataFrame

In [136]:
df[['FlightDate', 'Airline', 'Origin']] # Subset of flightdate, airline and origin columns

       FlightDate            Airline Origin
0      2020-09-01        Comair Inc.    PHL
1      2020-09-02        Comair Inc.    PHL
2      2020-09-03        Comair Inc.    PHL
3      2020-09-04        Comair Inc.    PHL
4      2020-09-05        Comair Inc.    PHL
...           ...                ...    ...
331233 2020-04-01  Republic Airlines    CLT
331234 2020-04-01  Republic Airlines    CLE
331235 2020-04-01  Republic Airlines    BUF
331236 2020-04-01  Republic Airlines    HRL
331237 2020-04-01  Republic Airlines    DCA

[5022397 rows x 3 columns]

In [137]:
df.columns[:5] # Gives a slice of first fivedf[df.columns[:5]]

Index(['FlightDate', 'Airline', 'Origin', 'Dest', 'Cancelled'], dtype='object')

In [138]:
df[df.columns[:5]]

       FlightDate            Airline Origin Dest  Cancelled
0      2020-09-01        Comair Inc.    PHL  DAY      False
1      2020-09-02        Comair Inc.    PHL  DAY      False
2      2020-09-03        Comair Inc.    PHL  DAY      False
3      2020-09-04        Comair Inc.    PHL  DAY      False
4      2020-09-05        Comair Inc.    PHL  DAY      False
...           ...                ...    ...  ...        ...
331233 2020-04-01  Republic Airlines    CLT  DEN       True
331234 2020-04-01  Republic Airlines    CLE  EWR      False
331235 2020-04-01  Republic Airlines    BUF  EWR      False
331236 2020-04-01  Republic Airlines    HRL  IAH      False
331237 2020-04-01  Republic Airlines    DCA  ORD      False

[5022397 rows x 5 columns]

In [139]:
df[df.columns[-5:]] # last 5 columns

,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,0.0,-2.0,2000-2059,2,0.0
1,0.0,-2.0,2000-2059,2,0.0
2,1.0,1.0,2000-2059,2,0.0
3,0.0,-2.0,2000-2059,2,0.0
4,0.0,-2.0,2000-2059,2,0.0
...,...,...,...,...,...
331233,NaN,NaN,1800-1859,6,0.0
331234,0.0,-2.0,1800-1859,2,0.0
331235,1.0,8.0,0800-0859,2,0.0
331236,0.0,-2.0,0800-0859,2,0.0
331237,0.0,-2.0,0900-0959,3,0.0

In [140]:
[c for c in df.columns if 'Time' in c] # List comprehension, filter columns that have Time in name

['CRSDepTime',
 'DepTime',
 'ArrTime',
 'AirTime',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'DepTimeBlk',
 'CRSArrTime',
 'ArrTimeBlk']

In [141]:
df.select_dtypes('int') # gives subset depending on data type

,CRSDepTime,Year,Quarter,Month,DayofMonth,DayOfWeek,DOT_ID_Marketing_Airline,Flight_Number_Marketing_Airline,DOT_ID_Operating_Airline,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginStateFips,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestStateFips,DestWac,CRSArrTime,DistanceGroup
0,1905,2020,3,9,1,2,19805,5020,20397,5020,14100,1410005,34100,42,23,11267,1126702,31267,39,44,2056,2
1,1905,2020,3,9,2,3,19805,5020,20397,5020,14100,1410005,34100,42,23,11267,1126702,31267,39,44,2056,2
2,1905,2020,3,9,3,4,19805,5020,20397,5020,14100,1410005,34100,42,23,11267,1126702,31267,39,44,2056,2
3,1905,2020,3,9,4,5,19805,5020,20397,5020,14100,1410005,34100,42,23,11267,1126702,31267,39,44,2056,2
4,1905,2020,3,9,5,6,19805,5020,20397,5020,14100,1410005,34100,42,23,11267,1126702,31267,39,44,2056,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331233,1645,2020,2,4,1,3,19977,3404,20452,3404,11057,1105703,31057,37,36,11292,1129202,30325,8,82,1840,6
331234,1700,2020,2,4,1,3,19977,3403,20452,3403,11042,1104205,30647,39,44,11618,1161802,31703,34,21,1847,2
331235,700,2020,2,4,1,3,19977,3402,20452,3402,10792,1079206,30792,36,22,11618,1161802,31703,34,21,828,2
331236,730,2020,2,4,1,3,19977,3401,20452,3401,12206,1220605,32206,48,74,12266,1226603,31453,48,74,848,2
331237,845,2020,2,4,1,3,19977,3400,20452,3400,11278,1127805,30852,51,38,13930,1393007,30977,17,41,957,3

In [142]:
df['Airline'] # provides just a series

0               Comair Inc.
1               Comair Inc.
2               Comair Inc.
3               Comair Inc.
4               Comair Inc.
                ...
331233    Republic Airlines
331234    Republic Airlines
331235    Republic Airlines
331236    Republic Airlines
331237    Republic Airlines
Name: Airline, Length: 5022397, dtype: object

In [143]:
df[['Airline']] # provides a dataframe

                  Airline
0             Comair Inc.
1             Comair Inc.
2             Comair Inc.
3             Comair Inc.
4             Comair Inc.
...                   ...
331233  Republic Airlines
331234  Republic Airlines
331235  Republic Airlines
331236  Republic Airlines
331237  Republic Airlines

[5022397 rows x 1 columns]

# Filtering Rows
df.loc[] name 
df.iloc() index location

In [144]:
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2020-09-01,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2034.0,0.0,76.0,111.0,96.0,477.0,2020,3,9,1,2,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N506AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2030.0,4.0,2056,-22.0,0.0,-2.0,2000-2059,2,0.0
1,2020-09-02,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2027.0,0.0,68.0,111.0,89.0,477.0,2020,3,9,2,3,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N512AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2022.0,5.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0
2,2020-09-03,Comair Inc.,PHL,DAY,False,False,1905,1855.0,0.0,-10.0,2122.0,26.0,77.0,111.0,147.0,477.0,2020,3,9,3,4,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N710PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,65.0,2000.0,2117.0,5.0,2056,26.0,1.0,1.0,2000-2059,2,0.0
3,2020-09-04,Comair Inc.,PHL,DAY,False,False,1905,1857.0,0.0,-8.0,2027.0,0.0,73.0,111.0,90.0,477.0,2020,3,9,4,5,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N712PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,13.0,1910.0,2023.0,4.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0
4,2020-09-05,Comair Inc.,PHL,DAY,False,False,1905,1856.0,0.0,-9.0,2026.0,0.0,72.0,111.0,90.0,477.0,2020,3,9,5,6,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N705PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,14.0,1910.0,2022.0,4.0,2056,-30.0,0.0,-2.0,2000-2059,2,0.0

In [145]:
df.iloc[1, 3]

'DAY'

In [146]:
df.iloc[:5, :5] # locate first 5 rows and columns

  FlightDate      Airline Origin Dest  Cancelled
0 2020-09-01  Comair Inc.    PHL  DAY      False
1 2020-09-02  Comair Inc.    PHL  DAY      False
2 2020-09-03  Comair Inc.    PHL  DAY      False
3 2020-09-04  Comair Inc.    PHL  DAY      False
4 2020-09-05  Comair Inc.    PHL  DAY      False

In [147]:
df.iloc[5] # only row number 5

FlightDate            2020-09-06 00:00:00
Airline                       Comair Inc.
Origin                                PHL
Dest                                  DAY
Cancelled                           False
                             ...
ArrDel15                              0.0
ArrivalDelayGroups                   -2.0
ArrTimeBlk                      2000-2059
DistanceGroup                           2
DivAirportLandings                    0.0
Name: 5, Length: 61, dtype: object

In [148]:
df.iloc[[5]] # as DataFrame

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
5,2020-09-06,Comair Inc.,PHL,DAY,False,False,1905,1853.0,0.0,-12.0,2023.0,0.0,70.0,111.0,90.0,477.0,2020,3,9,6,7,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N710PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,13.0,1906.0,2016.0,7.0,2056,-33.0,0.0,-2.0,2000-2059,2,0.0

In [149]:
df.iloc[:, 1] # Filters only to a column, column 1 here

0               Comair Inc.
1               Comair Inc.
2               Comair Inc.
3               Comair Inc.
4               Comair Inc.
                ...
331233    Republic Airlines
331234    Republic Airlines
331235    Republic Airlines
331236    Republic Airlines
331237    Republic Airlines
Name: Airline, Length: 5022397, dtype: object

In [150]:
df.iloc[:, [1,2]] # as a dataframe, columns 1 and 2 here

                  Airline Origin
0             Comair Inc.    PHL
1             Comair Inc.    PHL
2             Comair Inc.    PHL
3             Comair Inc.    PHL
4             Comair Inc.    PHL
...                   ...    ...
331233  Republic Airlines    CLT
331234  Republic Airlines    CLE
331235  Republic Airlines    BUF
331236  Republic Airlines    HRL
331237  Republic Airlines    DCA

[5022397 rows x 2 columns]

In [151]:
df.loc[:, ['Airline', 'Origin']] # use names of columns with loc

                  Airline Origin
0             Comair Inc.    PHL
1             Comair Inc.    PHL
2             Comair Inc.    PHL
3             Comair Inc.    PHL
4             Comair Inc.    PHL
...                   ...    ...
331233  Republic Airlines    CLT
331234  Republic Airlines    CLE
331235  Republic Airlines    BUF
331236  Republic Airlines    HRL
331237  Republic Airlines    DCA

[5022397 rows x 2 columns]

In [152]:
df['Airline'] == 'Spirit Air Lines'

0         False
1         False
2         False
3         False
4         False
          ...
331233    False
331234    False
331235    False
331236    False
331237    False
Name: Airline, Length: 5022397, dtype: bool

In [153]:
df.loc[df['Airline'] == 'Spirit Air Lines'] # shows only when boolean is true, can use & | to filter multiple columns

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
139073,2020-09-09,Spirit Air Lines,FLL,ORD,False,False,2020,2020.0,0.0,0.0,2210.0,0.0,153.0,194.0,170.0,1182.0,2020,3,9,9,3,NK,NK,20416,NK,1,NK,20416,NK,N627NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,0.0,2000-2059,10.0,2030.0,2203.0,7.0,2234,-24.0,0.0,-2.0,2200-2259,5,0.0
139074,2020-09-10,Spirit Air Lines,FLL,ORD,False,False,2020,2015.0,0.0,-5.0,2213.0,0.0,157.0,194.0,178.0,1182.0,2020,3,9,10,4,NK,NK,20416,NK,1,NK,20416,NK,N604NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,2000-2059,15.0,2030.0,2207.0,6.0,2234,-21.0,0.0,-2.0,2200-2259,5,0.0
139075,2020-09-11,Spirit Air Lines,FLL,ORD,False,False,2020,2015.0,0.0,-5.0,2210.0,0.0,159.0,194.0,175.0,1182.0,2020,3,9,11,5,NK,NK,20416,NK,1,NK,20416,NK,N624NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,2000-2059,10.0,2025.0,2204.0,6.0,2234,-24.0,0.0,-2.0,2200-2259,5,0.0
139076,2020-09-12,Spirit Air Lines,FLL,ORD,False,False,2020,2018.0,0.0,-2.0,2211.0,0.0,151.0,194.0,173.0,1182.0,2020,3,9,12,6,NK,NK,20416,NK,1,NK,20416,NK,N633NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,2000-2059,13.0,2031.0,2202.0,9.0,2234,-23.0,0.0,-2.0,2200-2259,5,0.0
139077,2020-09-13,Spirit Air Lines,FLL,ORD,False,False,2020,2017.0,0.0,-3.0,2204.0,0.0,150.0,194.0,167.0,1182.0,2020,3,9,13,7,NK,NK,20416,NK,1,NK,20416,NK,N673NK,1,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,2000-2059,9.0,2026.0,2156.0,8.0,2234,-30.0,0.0,-2.0,2200-2259,5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23900,2020-04-30,Spirit Air Lines,PHL,FLL,False,False,1925,1924.0,0.0,-1.0,2212.0,0.0,147.0,171.0,168.0,992.0,2020,2,4,30,4,NK,NK,20416,NK,3051,NK,20416,NK,N656NK,3051,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,0.0,-1.0,1900-1959,14.0,1938.0,2205.0,7.0,2216,-4.0,0.0,-1.0,2200-2259,4,0.0
23901,2020-04-09,Spirit Air Lines,LAS,IAH,False,False,1359,1410.0,11.0,11.0,1921.0,22.0,169.0,180.0,191.0,1222.0,2020,2,4,9,4,NK,NK,20416,NK,1292,NK,20416,NK,N523NK,1292,12889,1288903,32211,"Las Vegas, NV",NV,32,Nevada,85,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,0.0,1300-1359,11.0,1421.0,1910.0,11.0,1859,22.0,1.0,1.0,1800-1859,5,0.0
23902,2020-04-18,Spirit Air Lines,FLL,PHL,False,False,1545,1553.0,8.0,8.0,1829.0,0.0,137.0,165.0,156.0,992.0,2020,2,4,18,6,NK,NK,20416,NK,3050,NK,20416,NK,N698NK,3050,11697,1169706,32467,"Fort Lauderdale, FL",FL,12,Florida,33,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,0.0,0.0,1500-1559,14.0,1607.0,1824.0,5.0,1830,-1.0,0.0,-1.0,1800-1859,4,0.0
23903,2020-04-29,Spirit Air Lines,LAX,DTW,False,True,2159,2154.0,0.0,-5.0,729.0,NaN,NaN,264.0,NaN,1979.0,2020,2,4,29,3,NK,NK,20416,NK,709,NK,20416,NK,N609NK,709,12892,1289208,32575,"Los Angeles, CA",CA,6,California,91,11433,1143302,31295,"Detroit, MI",MI,26,Michigan,43,0.0,-1.0,2100-2159,11.0,2205.0,722.0,7.0,523,NaN,NaN,NaN,0001-0559,8,1.0
23904,2020-04-02,Spirit Air Lines,DFW,ORD,False,False,600,608.0,8.0,8.0,809.0,0.0,106.0,145.0,121.0,801.0,2020,2,4,2,4,NK,NK,20416,NK,940,NK,20416,NK,N517NK,940,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,0.0,0600-0659,10.0,618.0,804.0,5.0,825,-16.0,0.0,-2.0,0800-0859,4,0.0

In [154]:
df.loc[~(df['Airline'] == 'Spirit Air Lines')] # use ~ to get only false values,

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2020-09-01,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2034.0,0.0,76.0,111.0,96.0,477.0,2020,3,9,1,2,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N506AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2030.0,4.0,2056,-22.0,0.0,-2.0,2000-2059,2,0.0
1,2020-09-02,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2027.0,0.0,68.0,111.0,89.0,477.0,2020,3,9,2,3,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N512AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2022.0,5.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0
2,2020-09-03,Comair Inc.,PHL,DAY,False,False,1905,1855.0,0.0,-10.0,2122.0,26.0,77.0,111.0,147.0,477.0,2020,3,9,3,4,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N710PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,65.0,2000.0,2117.0,5.0,2056,26.0,1.0,1.0,2000-2059,2,0.0
3,2020-09-04,Comair Inc.,PHL,DAY,False,False,1905,1857.0,0.0,-8.0,2027.0,0.0,73.0,111.0,90.0,477.0,2020,3,9,4,5,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N712PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,13.0,1910.0,2023.0,4.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0
4,2020-09-05,Comair Inc.,PHL,DAY,False,False,1905,1856.0,0.0,-9.0,2026.0,0.0,72.0,111.0,90.0,477.0,2020,3,9,5,6,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N705PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,14.0,1910.0,2022.0,4.0,2056,-30.0,0.0,-2.0,2000-2059,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331233,2020-04-01,Republic Airlines,CLT,DEN,True,False,1645,NaN,NaN,NaN,NaN,NaN,NaN,235.0,NaN,1337.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3404,YX,20452,YX,N648RW,3404,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,NaN,NaN,1600-1659,NaN,NaN,NaN,NaN,1840,NaN,NaN,NaN,1800-1859,6,0.0
331234,2020-04-01,Republic Airlines,CLE,EWR,False,False,1700,1652.0,0.0,-8.0,1812.0,0.0,61.0,107.0,80.0,404.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3403,YX,20452,YX,N645RW,3403,11042,1104205,30647,"Cleveland, OH",OH,39,Ohio,44,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,0.0,-1.0,1700-1759,13.0,1705.0,1806.0,6.0,1847,-35.0,0.0,-2.0,1800-1859,2,0.0
331235,2020-04-01,Republic Airlines,BUF,EWR,False,False,700,933.0,153.0,153.0,1040.0,132.0,55.0,88.0,67.0,282.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3402,YX,20452,YX,N725YX,3402,10792,1079206,30792,"Buffalo, NY",NY,36,New York,22,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,10.0,0700-0759,8.0,941.0,1036.0,4.0,828,132.0,1.0,8.0,0800-0859,2,0.0
331236,2020-04-01,Republic Airlines,HRL,IAH,False,False,730,720.0,0.0,-10.0,831.0,0.0,52.0,78.0,71.0,295.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3401,YX,20452,YX,N730YX,3401,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,11.0,731.0,823.0,8.0,848,-17.0,0.0,-2.0,0800-0859,2,0.0
331237,2020-04-01,Republic Airlines,DCA,ORD,False,False,845,837.0,0.0,-8.0,930.0,0.0,96.0,132.0,113.0,612.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3400,YX,20452,YX,N861RW,3400,11278,1127805,30852,"Washington, DC",VA,51,Virginia,38,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,0800-0859,10.0,847.0,923.0,7.0,957,-27.0,0.0,-2.0,0900-0959,3,0.0

In [155]:
# Filter using query
df.query('DepTime > 1130')

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
0,2020-09-01,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2034.0,0.0,76.0,111.0,96.0,477.0,2020,3,9,1,2,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N506AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2030.0,4.0,2056,-22.0,0.0,-2.0,2000-2059,2,0.0
1,2020-09-02,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2027.0,0.0,68.0,111.0,89.0,477.0,2020,3,9,2,3,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N512AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2022.0,5.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0
2,2020-09-03,Comair Inc.,PHL,DAY,False,False,1905,1855.0,0.0,-10.0,2122.0,26.0,77.0,111.0,147.0,477.0,2020,3,9,3,4,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N710PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,65.0,2000.0,2117.0,5.0,2056,26.0,1.0,1.0,2000-2059,2,0.0
3,2020-09-04,Comair Inc.,PHL,DAY,False,False,1905,1857.0,0.0,-8.0,2027.0,0.0,73.0,111.0,90.0,477.0,2020,3,9,4,5,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N712PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,13.0,1910.0,2023.0,4.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0
4,2020-09-05,Comair Inc.,PHL,DAY,False,False,1905,1856.0,0.0,-9.0,2026.0,0.0,72.0,111.0,90.0,477.0,2020,3,9,5,6,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N705PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,14.0,1910.0,2022.0,4.0,2056,-30.0,0.0,-2.0,2000-2059,2,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331221,2020-04-01,Republic Airlines,EWR,MSP,False,False,1325,1317.0,0.0,-8.0,1455.0,0.0,143.0,184.0,158.0,1008.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3424,YX,20452,YX,N725YX,3424,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,13487,1348702,31650,"Minneapolis, MN",MN,27,Minnesota,63,0.0,-1.0,1300-1359,11.0,1328.0,1451.0,4.0,1529,-34.0,0.0,-2.0,1500-1559,5,0.0
331222,2020-04-01,Republic Airlines,DEN,CVG,False,False,1841,1838.0,0.0,-3.0,2313.0,0.0,130.0,173.0,155.0,1069.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3423,YX,20452,YX,N642RW,3423,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,11193,1119302,33105,"Cincinnati, OH",KY,21,Kentucky,52,0.0,-1.0,1800-1859,20.0,1858.0,2308.0,5.0,2334,-21.0,0.0,-2.0,2300-2359,5,0.0
331229,2020-04-01,Republic Airlines,SAT,EWR,False,False,1308,1259.0,0.0,-9.0,1723.0,0.0,190.0,235.0,204.0,1569.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3414,YX,20452,YX,N635RW,3414,14683,1468305,33214,"San Antonio, TX",TX,48,Texas,74,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,0.0,-1.0,1300-1359,9.0,1308.0,1718.0,5.0,1803,-40.0,0.0,-2.0,1800-1859,7,0.0
331230,2020-04-01,Republic Airlines,MSP,IAD,False,False,1235,1228.0,0.0,-7.0,1537.0,0.0,113.0,146.0,129.0,908.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3413,YX,20452,YX,N740YX,3413,13487,1348702,31650,"Minneapolis, MN",MN,27,Minnesota,63,12264,1226402,30852,"Washington, DC",VA,51,Virginia,38,0.0,-1.0,1200-1259,9.0,1237.0,1530.0,7.0,1601,-24.0,0.0,-2.0,1600-1659,4,0.0
331234,2020-04-01,Republic Airlines,CLE,EWR,False,False,1700,1652.0,0.0,-8.0,1812.0,0.0,61.0,107.0,80.0,404.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3403,YX,20452,YX,N645RW,3403,11042,1104205,30647,"Cleveland, OH",OH,39,Ohio,44,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,0.0,-1.0,1700-1759,13.0,1705.0,1806.0,6.0,1847,-35.0,0.0,-2.0,1800-1859,2,0.0

In [156]:
df.query('(DepTime > 1130) and (Origin == "DRO")') # can take multiple expression

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings
293849,2020-09-01,SkyWest Airlines Inc.,DRO,DFW,False,False,1448,1914.0,266.0,266.0,2210.0,263.0,90.0,119.0,116.0,674.0,2020,3,9,1,2,AA,AA_CODESHARE,19805,AA,3199,OO,20304,OO,N759EV,3199,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,1.0,12.0,1400-1459,10.0,1924.0,2154.0,16.0,1747,263.0,1.0,12.0,1700-1759,3,0.0
294045,2020-09-02,SkyWest Airlines Inc.,DRO,DFW,False,False,1448,1438.0,0.0,-10.0,1733.0,0.0,87.0,119.0,115.0,674.0,2020,3,9,2,3,AA,AA_CODESHARE,19805,AA,3199,OO,20304,OO,N773SK,3199,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,0.0,-1.0,1400-1459,18.0,1456.0,1723.0,10.0,1747,-14.0,0.0,-1.0,1700-1759,3,0.0
294263,2020-09-03,SkyWest Airlines Inc.,DRO,DFW,False,False,1448,1456.0,8.0,8.0,1802.0,15.0,91.0,119.0,126.0,674.0,2020,3,9,3,4,AA,AA_CODESHARE,19805,AA,3199,OO,20304,OO,N740EV,3199,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,0.0,0.0,1400-1459,27.0,1523.0,1754.0,8.0,1747,15.0,1.0,1.0,1700-1759,3,0.0
294485,2020-09-04,SkyWest Airlines Inc.,DRO,DFW,False,False,1448,1440.0,0.0,-8.0,1731.0,0.0,90.0,119.0,111.0,674.0,2020,3,9,4,5,AA,AA_CODESHARE,19805,AA,3199,OO,20304,OO,N740EV,3199,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,0.0,-1.0,1400-1459,13.0,1453.0,1723.0,8.0,1747,-16.0,0.0,-2.0,1700-1759,3,0.0
294669,2020-09-05,SkyWest Airlines Inc.,DRO,DFW,False,False,1448,1439.0,0.0,-9.0,1749.0,2.0,109.0,119.0,130.0,674.0,2020,3,9,5,6,AA,AA_CODESHARE,19805,AA,3199,OO,20304,OO,N773SK,3199,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,0.0,-1.0,1400-1459,12.0,1451.0,1740.0,9.0,1747,2.0,0.0,0.0,1700-1759,3,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315546,2020-04-03,Mesa Airlines Inc.,DRO,PHX,False,False,1856,1836.0,0.0,-20.0,1857.0,0.0,60.0,88.0,81.0,351.0,2020,2,4,3,5,AA,AA_CODESHARE,19805,AA,5801,YV,20378,YV,N914FJ,5801,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,0.0,-2.0,1800-1859,12.0,1848.0,1848.0,9.0,1924,-27.0,0.0,-2.0,1900-1959,2,0.0
315548,2020-04-05,Mesa Airlines Inc.,DRO,PHX,False,False,1856,1844.0,0.0,-12.0,1908.0,0.0,66.0,88.0,84.0,351.0,2020,2,4,5,7,AA,AA_CODESHARE,19805,AA,5801,YV,20378,YV,N925FJ,5801,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,0.0,-1.0,1800-1859,10.0,1854.0,1900.0,8.0,1924,-16.0,0.0,-2.0,1900-1959,2,0.0
315549,2020-04-06,Mesa Airlines Inc.,DRO,PHX,False,False,1856,1842.0,0.0,-14.0,1905.0,0.0,61.0,88.0,83.0,351.0,2020,2,4,6,1,AA,AA_CODESHARE,19805,AA,5801,YV,20378,YV,N946LR,5801,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,0.0,-1.0,1800-1859,11.0,1853.0,1854.0,11.0,1924,-19.0,0.0,-2.0,1900-1959,2,0.0
317495,2020-04-02,Mesa Airlines Inc.,DRO,PHX,False,False,1200,1148.0,0.0,-12.0,1209.0,0.0,59.0,81.0,81.0,351.0,2020,2,4,2,4,AA,AA_CODESHARE,19805,AA,5878,YV,20378,YV,N944LR,5878,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,0.0,-1.0,1200-1259,13.0,1201.0,1200.0,9.0,1221,-12.0,0.0,-1.0,1200-1259,2,0.0
317499,2020-04-06,Mesa Airlines Inc.,DRO,PHX,False,False,1200,1138.0,0.0,-22.0,1153.0,0.0,58.0,81.0,75.0,351.0,2020,2,4,6,1,AA,AA_CODESHARE,19805,AA,5878,YV,20378,YV,N912FJ,5878,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,14107,1410702,30466,"Phoenix, AZ",AZ,4,Arizona,81,0.0,-2.0,1200-1259,10.0,1148.0,1146.0,7.0,1221,-28.0,0.0,-2.0,1200-1259,2,0.0

# Summerizing Data

In [157]:
df['DepTime'].mean()

1312.7056392880713

In [158]:
df['DepTime'].min()

1.0

In [159]:
df['DepTime'].max()

2400.0

In [160]:
df['DepTime'].std()

466.968910741278

In [161]:
df['DepTime'].var()

218059.9635988957

In [162]:
df['DepTime'].count()

4722777

In [163]:
df['DepTime'].sum()

6199616001.0

In [164]:
df['DepTime'].quantile()

1313.0

In [165]:
df['DepTime'].quantile([0.25, 0.75])

0.25     924.0
0.75    1712.0
Name: DepTime, dtype: float64

In [166]:
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].agg(['mean', 'min', 'max']) # df with stats and columns specified

          DepTime    DepDelay      ArrTime     ArrDelay
mean  1312.705639     2.06478  1480.713918    -4.863644
min      1.000000  -131.00000     1.000000  -139.000000
max   2400.000000  3890.00000  2400.000000  3864.000000

In [167]:
df[['DepTime', 'DepDelay', 'ArrTime', 'ArrDelay']].agg(
    {'DepTime': ['min', 'max'],
     'DepDelay': ['mean'],
     'ArrTime': ['mean', 'min', 'max']
    }
) # can take dictionaries with specified aggregations

      DepTime  DepDelay      ArrTime
min       1.0       NaN     1.000000
max    2400.0       NaN  2400.000000
mean      NaN   2.06478  1480.713918

# Summerizing Categorical Variables

In [168]:
df['Airline'].unique() # array of unique fields

array(['Comair Inc.', 'Frontier Airlines Inc.', 'Alaska Airlines Inc.',
       'Horizon Air', 'Southwest Airlines Co.', 'United Air Lines Inc.',
       'Commutair Aka Champlain Enterprises, Inc.',
       'Air Wisconsin Airlines Corp',
       'GoJet Airlines, LLC d/b/a United Express',
       'SkyWest Airlines Inc.', 'Republic Airlines', 'Mesa Airlines Inc.',
       'Spirit Air Lines', 'ExpressJet Airlines Inc.',
       'American Airlines Inc.', 'Capital Cargo International',
       'Envoy Air', 'Endeavor Air Inc.', 'Hawaiian Airlines Inc.',
       'Empire Airlines Inc.', 'JetBlue Airways', 'Delta Air Lines Inc.',
       'Allegiant Air', 'Compass Airlines', 'Trans States Airlines'],
      dtype=object)

In [169]:
df['Airline'].value_counts() # Number of counts per field

Airline
Southwest Airlines Co.                       961276
SkyWest Airlines Inc.                        596986
Delta Air Lines Inc.                         581101
American Airlines Inc.                       569806
United Air Lines Inc.                        308217
Republic Airlines                            219772
Endeavor Air Inc.                            211457
Envoy Air                                    211435
Comair Inc.                                  192613
JetBlue Airways                              144163
Alaska Airlines Inc.                         138226
Mesa Airlines Inc.                           135927
Spirit Air Lines                             135102
Allegiant Air                                 98489
Horizon Air                                   96063
Frontier Airlines Inc.                        91175
Capital Cargo International                   72359
Air Wisconsin Airlines Corp                   53989
ExpressJet Airlines Inc.                      52212
Hawaiian Airlines Inc.                        40414
GoJet Airlines, LLC d/b/a United Express      38989
Commutair Aka Champlain Enterprises, Inc.     32953
Trans States Airlines                         18705
Compass Airlines                              15878
Empire Airlines Inc.                           5090
Name: count, dtype: int64

In [170]:
df['Airline'].value_counts(normalize=True) # Fractional Value

Airline
Southwest Airlines Co.                       0.191398
SkyWest Airlines Inc.                        0.118865
Delta Air Lines Inc.                         0.115702
American Airlines Inc.                       0.113453
United Air Lines Inc.                        0.061369
Republic Airlines                            0.043758
Endeavor Air Inc.                            0.042103
Envoy Air                                    0.042098
Comair Inc.                                  0.038351
JetBlue Airways                              0.028704
Alaska Airlines Inc.                         0.027522
Mesa Airlines Inc.                           0.027064
Spirit Air Lines                             0.026900
Allegiant Air                                0.019610
Horizon Air                                  0.019127
Frontier Airlines Inc.                       0.018154
Capital Cargo International                  0.014407
Air Wisconsin Airlines Corp                  0.010750
ExpressJet Airlines Inc.                     0.010396
Hawaiian Airlines Inc.                       0.008047
GoJet Airlines, LLC d/b/a United Express     0.007763
Commutair Aka Champlain Enterprises, Inc.    0.006561
Trans States Airlines                        0.003724
Compass Airlines                             0.003161
Empire Airlines Inc.                         0.001013
Name: proportion, dtype: float64

In [171]:
df[['Airline', 'Origin']].value_counts().reset_index() # count of column combonations

                                       Airline Origin   count
0                         Delta Air Lines Inc.    ATL  148582
1                       American Airlines Inc.    DFW  105413
2                                  Comair Inc.    CLT   70955
3                       American Airlines Inc.    CLT   70444
4                       Southwest Airlines Co.    DEN   62969
...                                        ...    ...     ...
2482  GoJet Airlines, LLC d/b/a United Express    BWI       1
2483                  ExpressJet Airlines Inc.    CRW       1
2484  GoJet Airlines, LLC d/b/a United Express    BOI       1
2485                  ExpressJet Airlines Inc.    HPN       1
2486                         Republic Airlines    FLL       1

[2487 rows x 3 columns]

# Advanced Column Operations

In [172]:
df[['CRSDepTime']].rank() # compute numerical data ranks

        CRSDepTime
0        4374040.5
1        4374040.5
2        4374040.5
3        4374040.5
4        4374040.5
...            ...
331233   3631530.5
331234   3710177.5
331235    448047.5
331236    640569.5
331237   1046960.5

[5022397 rows x 1 columns]

In [173]:
df[['CRSDepTime']].rank(method='dense')

        CRSDepTime
0           1028.0
1           1028.0
2           1028.0
3           1028.0
4           1028.0
...            ...
331233       888.0
331234       903.0
331235       303.0
331236       333.0
331237       408.0

[5022397 rows x 1 columns]

In [174]:
df[['CRSDepTime']].rank(method='first')

        CRSDepTime
0        4368399.0
1        4368400.0
2        4368401.0
3        4368402.0
4        4368403.0
...            ...
331233   3641551.0
331234   3726371.0
331235    497624.0
331236    658770.0
331237   1057223.0

[5022397 rows x 1 columns]

In [175]:
df[['CRSDepTime']].shift(-1) # shift values by number provided (positivee or negative)

        CRSDepTime
0           1905.0
1           1905.0
2           1905.0
3           1905.0
4           1905.0
...            ...
331233      1700.0
331234       700.0
331235       730.0
331236       845.0
331237         NaN

[5022397 rows x 1 columns]

In [176]:
df[['CRSDepTime']].rank().cumsum() # cumilitive sum, max and min

          CRSDepTime
0       4.374040e+06
1       8.748081e+06
2       1.312212e+07
3       1.749616e+07
4       2.187020e+07
...              ...
331233  1.261223e+13
331234  1.261224e+13
331235  1.261224e+13
331236  1.261224e+13
331237  1.261224e+13

[5022397 rows x 1 columns]

# Rolling Methods

In [177]:
df[['DepDelayMinutes']].rolling(window=5).mean() # rolling window calculations

        DepDelayMinutes
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   0.0
...                 ...
331233              NaN
331234              NaN
331235              NaN
331236              NaN
331237              NaN

[5022397 rows x 1 columns]

In [178]:
df[['DepTime']].clip(1000,2000) # clip values, anything below is 1000 and anything greater is 2000

        DepTime
0        1858.0
1        1858.0
2        1855.0
3        1857.0
4        1856.0
...         ...
331233      NaN
331234   1652.0
331235   1000.0
331236   1000.0
331237   1000.0

[5022397 rows x 1 columns]

# Groupby Methods

In [179]:
df.groupby('Airline')[['DepTime']].mean()
# (single or multiple column name in list to groupby)[column or list to run aggregations one]

                                               DepTime
Airline
Air Wisconsin Airlines Corp                1321.295240
Alaska Airlines Inc.                       1298.467172
Allegiant Air                              1333.310275
American Airlines Inc.                     1288.514821
Capital Cargo International                1313.109379
Comair Inc.                                1324.376547
Commutair Aka Champlain Enterprises, Inc.  1357.240204
Compass Airlines                           1335.991830
Delta Air Lines Inc.                       1313.227938
Empire Airlines Inc.                       1285.356617
Endeavor Air Inc.                          1324.766225
Envoy Air                                  1288.261092
ExpressJet Airlines Inc.                   1320.122422
Frontier Airlines Inc.                     1336.707201
GoJet Airlines, LLC d/b/a United Express   1293.266856
Hawaiian Airlines Inc.                     1275.890901
Horizon Air                                1318.785274
JetBlue Airways                            1320.271169
Mesa Airlines Inc.                         1320.845998
Republic Airlines                          1300.953743
SkyWest Airlines Inc.                      1310.878968
Southwest Airlines Co.                     1328.818058
Spirit Air Lines                           1333.404684
Trans States Airlines                      1292.293011
United Air Lines Inc.                      1295.338308

In [180]:
df.groupby('Airline')[['DepTime']].agg(['min','max'])

                                          DepTime
                                              min     max
Airline
Air Wisconsin Airlines Corp                   1.0  2353.0
Alaska Airlines Inc.                          1.0  2400.0
Allegiant Air                                 1.0  2400.0
American Airlines Inc.                        1.0  2400.0
Capital Cargo International                   2.0  2357.0
Comair Inc.                                   1.0  2400.0
Commutair Aka Champlain Enterprises, Inc.     1.0  2359.0
Compass Airlines                             12.0  2358.0
Delta Air Lines Inc.                          1.0  2400.0
Empire Airlines Inc.                        545.0  2343.0
Endeavor Air Inc.                             1.0  2400.0
Envoy Air                                     3.0  2400.0
ExpressJet Airlines Inc.                      5.0  2359.0
Frontier Airlines Inc.                        1.0  2400.0
GoJet Airlines, LLC d/b/a United Express      1.0  2359.0
Hawaiian Airlines Inc.                        3.0  2350.0
Horizon Air                                   1.0  2400.0
JetBlue Airways                               1.0  2400.0
Mesa Airlines Inc.                            1.0  2359.0
Republic Airlines                             1.0  2400.0
SkyWest Airlines Inc.                         1.0  2400.0
Southwest Airlines Co.                        1.0  2400.0
Spirit Air Lines                              1.0  2400.0
Trans States Airlines                         2.0  2341.0
United Air Lines Inc.                         1.0  2359.0

In [181]:
df.groupby('Airline')[['DepTime', 'ArrTime']].agg(['mean', 'min','max'])
#                       Multi index columns

                                               DepTime                 \
                                                  mean    min     max
Airline
Air Wisconsin Airlines Corp                1321.295240    1.0  2353.0
Alaska Airlines Inc.                       1298.467172    1.0  2400.0
Allegiant Air                              1333.310275    1.0  2400.0
American Airlines Inc.                     1288.514821    1.0  2400.0
Capital Cargo International                1313.109379    2.0  2357.0
Comair Inc.                                1324.376547    1.0  2400.0
Commutair Aka Champlain Enterprises, Inc.  1357.240204    1.0  2359.0
Compass Airlines                           1335.991830   12.0  2358.0
Delta Air Lines Inc.                       1313.227938    1.0  2400.0
Empire Airlines Inc.                       1285.356617  545.0  2343.0
Endeavor Air Inc.                          1324.766225    1.0  2400.0
Envoy Air                                  1288.261092    3.0  2400.0
ExpressJet Airlines Inc.                   1320.122422    5.0  2359.0
Frontier Airlines Inc.                     1336.707201    1.0  2400.0
GoJet Airlines, LLC d/b/a United Express   1293.266856    1.0  2359.0
Hawaiian Airlines Inc.                     1275.890901    3.0  2350.0
Horizon Air                                1318.785274    1.0  2400.0
JetBlue Airways                            1320.271169    1.0  2400.0
Mesa Airlines Inc.                         1320.845998    1.0  2359.0
Republic Airlines                          1300.953743    1.0  2400.0
SkyWest Airlines Inc.                      1310.878968    1.0  2400.0
Southwest Airlines Co.                     1328.818058    1.0  2400.0
Spirit Air Lines                           1333.404684    1.0  2400.0
Trans States Airlines                      1292.293011    2.0  2341.0
United Air Lines Inc.                      1295.338308    1.0  2359.0

                                               ArrTime
                                                  mean   min     max
Airline
Air Wisconsin Airlines Corp                1456.296870   1.0  2359.0
Alaska Airlines Inc.                       1515.598929   1.0  2400.0
Allegiant Air                              1525.115595   1.0  2400.0
American Airlines Inc.                     1478.210643   1.0  2400.0
Capital Cargo International                1443.650380   1.0  2400.0
Comair Inc.                                1467.315174   1.0  2400.0
Commutair Aka Champlain Enterprises, Inc.  1498.839936   1.0  2359.0
Compass Airlines                           1497.168880   1.0  2400.0
Delta Air Lines Inc.                       1493.117439   1.0  2400.0
Empire Airlines Inc.                       1340.970657  14.0  2348.0
Endeavor Air Inc.                          1462.854656   1.0  2400.0
Envoy Air                                  1447.386828   1.0  2400.0
ExpressJet Airlines Inc.                   1479.253969   1.0  2400.0
Frontier Airlines Inc.                     1477.698696   1.0  2400.0
GoJet Airlines, LLC d/b/a United Express   1441.258687   1.0  2359.0
Hawaiian Airlines Inc.                     1419.141536   1.0  2400.0
Horizon Air                                1457.330539   1.0  2400.0
JetBlue Airways                            1462.254476   1.0  2400.0
Mesa Airlines Inc.                         1493.094863   1.0  2400.0
Republic Airlines                          1471.415806   1.0  2400.0
SkyWest Airlines Inc.                      1468.314651   1.0  2400.0
Southwest Airlines Co.                     1498.323202   1.0  2400.0
Spirit Air Lines                           1475.838254   1.0  2400.0
Trans States Airlines                      1448.711819   1.0  2359.0
United Air Lines Inc.                      1495.707079   1.0  2359.0

In [182]:
df_agg = df.groupby('Airline')[['DepTime', 'ArrTime']].agg(['mean', 'min','max'])

In [183]:
df_agg.columns.to_flat_index() # makes it a list of tuples

Index([('DepTime', 'mean'),  ('DepTime', 'min'),  ('DepTime', 'max'),
       ('ArrTime', 'mean'),  ('ArrTime', 'min'),  ('ArrTime', 'max')],
      dtype='object')

In [184]:
df_agg.columns = ['_'.join(c) for c in df_agg.columns] # rename columns so the names are flattened

In [185]:
df_agg

,DepTime_mean,DepTime_min,DepTime_max,ArrTime_mean,ArrTime_min,ArrTime_max
Airline,,,,,,
Air Wisconsin Airlines Corp,1321.295240,1.0,2353.0,1456.296870,1.0,2359.0
Alaska Airlines Inc.,1298.467172,1.0,2400.0,1515.598929,1.0,2400.0
Allegiant Air,1333.310275,1.0,2400.0,1525.115595,1.0,2400.0
American Airlines Inc.,1288.514821,1.0,2400.0,1478.210643,1.0,2400.0
Capital Cargo International,1313.109379,2.0,2357.0,1443.650380,1.0,2400.0
Comair Inc.,1324.376547,1.0,2400.0,1467.315174,1.0,2400.0
"Commutair Aka Champlain Enterprises, Inc.",1357.240204,1.0,2359.0,1498.839936,1.0,2359.0
Compass Airlines,1335.991830,12.0,2358.0,1497.168880,1.0,2400.0
Delta Air Lines Inc.,1313.227938,1.0,2400.0,1493.117439,1.0,2400.0
Empire Airlines Inc.,1285.356617,545.0,2343.0,1340.970657,14.0,2348.0
Endeavor Air Inc.,1324.766225,1.0,2400.0,1462.854656,1.0,2400.0
Envoy Air,1288.261092,3.0,2400.0,1447.386828,1.0,2400.0
ExpressJet Airlines Inc.,1320.122422,5.0,2359.0,1479.253969,1.0,2400.0
Frontier Airlines Inc.,1336.707201,1.0,2400.0,1477.698696,1.0,2400.0
"GoJet Airlines, LLC d/b/a United Express",1293.266856,1.0,2359.0,1441.258687,1.0,2359.0
Hawaiian Airlines Inc.,1275.890901,3.0,2350.0,1419.141536,1.0,2400.0
Horizon Air,1318.785274,1.0,2400.0,1457.330539,1.0,2400.0
JetBlue Airways,1320.271169,1.0,2400.0,1462.254476,1.0,2400.0
Mesa Airlines Inc.,1320.845998,1.0,2359.0,1493.094863,1.0,2400.0
Republic Airlines,1300.953743,1.0,2400.0,1471.415806,1.0,2400.0
SkyWest Airlines Inc.,1310.878968,1.0,2400.0,1468.314651,1.0,2400.0
Southwest Airlines Co.,1328.818058,1.0,2400.0,1498.323202,1.0,2400.0
Spirit Air Lines,1333.404684,1.0,2400.0,1475.838254,1.0,2400.0
Trans States Airlines,1292.293011,2.0,2341.0,1448.711819,1.0,2359.0
United Air Lines Inc.,1295.338308,1.0,2359.0,1495.707079,1.0,2359.0

# New Columns

In [186]:
df['DepTime2'] = df['DepTime'] /60 # adds new column to the end of dataframe

In [187]:
df.head()

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
0,2020-09-01,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2034.0,0.0,76.0,111.0,96.0,477.0,2020,3,9,1,2,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N506AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2030.0,4.0,2056,-22.0,0.0,-2.0,2000-2059,2,0.0,30.966667
1,2020-09-02,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2027.0,0.0,68.0,111.0,89.0,477.0,2020,3,9,2,3,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N512AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2022.0,5.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0,30.966667
2,2020-09-03,Comair Inc.,PHL,DAY,False,False,1905,1855.0,0.0,-10.0,2122.0,26.0,77.0,111.0,147.0,477.0,2020,3,9,3,4,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N710PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,65.0,2000.0,2117.0,5.0,2056,26.0,1.0,1.0,2000-2059,2,0.0,30.916667
3,2020-09-04,Comair Inc.,PHL,DAY,False,False,1905,1857.0,0.0,-8.0,2027.0,0.0,73.0,111.0,90.0,477.0,2020,3,9,4,5,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N712PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,13.0,1910.0,2023.0,4.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0,30.950000
4,2020-09-05,Comair Inc.,PHL,DAY,False,False,1905,1856.0,0.0,-9.0,2026.0,0.0,72.0,111.0,90.0,477.0,2020,3,9,5,6,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N705PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,14.0,1910.0,2022.0,4.0,2056,-30.0,0.0,-2.0,2000-2059,2,0.0,30.933333

In [188]:
df.assign(DepTime3 = df['DepTime']/2)
# new_column = new_values

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2,DepTime3
0,2020-09-01,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2034.0,0.0,76.0,111.0,96.0,477.0,2020,3,9,1,2,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N506AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2030.0,4.0,2056,-22.0,0.0,-2.0,2000-2059,2,0.0,30.966667,929.0
1,2020-09-02,Comair Inc.,PHL,DAY,False,False,1905,1858.0,0.0,-7.0,2027.0,0.0,68.0,111.0,89.0,477.0,2020,3,9,2,3,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N512AE,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,16.0,1914.0,2022.0,5.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0,30.966667,929.0
2,2020-09-03,Comair Inc.,PHL,DAY,False,False,1905,1855.0,0.0,-10.0,2122.0,26.0,77.0,111.0,147.0,477.0,2020,3,9,3,4,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N710PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,65.0,2000.0,2117.0,5.0,2056,26.0,1.0,1.0,2000-2059,2,0.0,30.916667,927.5
3,2020-09-04,Comair Inc.,PHL,DAY,False,False,1905,1857.0,0.0,-8.0,2027.0,0.0,73.0,111.0,90.0,477.0,2020,3,9,4,5,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N712PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,13.0,1910.0,2023.0,4.0,2056,-29.0,0.0,-2.0,2000-2059,2,0.0,30.950000,928.5
4,2020-09-05,Comair Inc.,PHL,DAY,False,False,1905,1856.0,0.0,-9.0,2026.0,0.0,72.0,111.0,90.0,477.0,2020,3,9,5,6,AA,AA_CODESHARE,19805,AA,5020,OH,20397,OH,N705PS,5020,14100,1410005,34100,"Philadelphia, PA",PA,42,Pennsylvania,23,11267,1126702,31267,"Dayton, OH",OH,39,Ohio,44,0.0,-1.0,1900-1959,14.0,1910.0,2022.0,4.0,2056,-30.0,0.0,-2.0,2000-2059,2,0.0,30.933333,928.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331233,2020-04-01,Republic Airlines,CLT,DEN,True,False,1645,NaN,NaN,NaN,NaN,NaN,NaN,235.0,NaN,1337.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3404,YX,20452,YX,N648RW,3404,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,NaN,NaN,1600-1659,NaN,NaN,NaN,NaN,1840,NaN,NaN,NaN,1800-1859,6,0.0,NaN,NaN
331234,2020-04-01,Republic Airlines,CLE,EWR,False,False,1700,1652.0,0.0,-8.0,1812.0,0.0,61.0,107.0,80.0,404.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3403,YX,20452,YX,N645RW,3403,11042,1104205,30647,"Cleveland, OH",OH,39,Ohio,44,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,0.0,-1.0,1700-1759,13.0,1705.0,1806.0,6.0,1847,-35.0,0.0,-2.0,1800-1859,2,0.0,27.533333,826.0
331235,2020-04-01,Republic Airlines,BUF,EWR,False,False,700,933.0,153.0,153.0,1040.0,132.0,55.0,88.0,67.0,282.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3402,YX,20452,YX,N725YX,3402,10792,1079206,30792,"Buffalo, NY",NY,36,New York,22,11618,1161802,31703,"Newark, NJ",NJ,34,New Jersey,21,1.0,10.0,0700-0759,8.0,941.0,1036.0,4.0,828,132.0,1.0,8.0,0800-0859,2,0.0,15.550000,466.5
331236,2020-04-01,Republic Airlines,HRL,IAH,False,False,730,720.0,0.0,-10.0,831.0,0.0,52.0,78.0,71.0,295.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3401,YX,20452,YX,N730YX,3401,12206,1220605,32206,"Harlingen/San Benito, TX",TX,48,Texas,74,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,0.0,-1.0,0700-0759,11.0,731.0,823.0,8.0,848,-17.0,0.0,-2.0,0800-0859,2,0.0,12.000000,360.0
331237,2020-04-01,Republic Airlines,DCA,ORD,False,False,845,837.0,0.0,-8.0,930.0,0.0,96.0,132.0,113.0,612.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3400,YX,20452,YX,N861RW,3400,11278,1127805,30852,"Washington, DC",VA,51,Virginia,38,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,0.0,-1.0,0800-0859,10.0,847.0,923.0,7.0,957,-27.0,0.0,-2.0,0900-0959,3,0.0,13.950000,418.5

# Sort Data

In [189]:
df.sort_values('ArrDelay', ascending=False)\
    .reset_index(drop=True)

# Sort by column, ascending Ture on default 
# Reset index value

,FlightDate,Airline,Origin,Dest,Cancelled,Diverted,CRSDepTime,DepTime,DepDelayMinutes,DepDelay,ArrTime,ArrDelayMinutes,AirTime,CRSElapsedTime,ActualElapsedTime,Distance,Year,Quarter,Month,DayofMonth,DayOfWeek,Marketing_Airline_Network,Operated_or_Branded_Code_Share_Partners,DOT_ID_Marketing_Airline,IATA_Code_Marketing_Airline,Flight_Number_Marketing_Airline,Operating_Airline,DOT_ID_Operating_Airline,IATA_Code_Operating_Airline,Tail_Number,Flight_Number_Operating_Airline,OriginAirportID,OriginAirportSeqID,OriginCityMarketID,OriginCityName,OriginState,OriginStateFips,OriginStateName,OriginWac,DestAirportID,DestAirportSeqID,DestCityMarketID,DestCityName,DestState,DestStateFips,DestStateName,DestWac,DepDel15,DepartureDelayGroups,DepTimeBlk,TaxiOut,WheelsOff,WheelsOn,TaxiIn,CRSArrTime,ArrDelay,ArrDel15,ArrivalDelayGroups,ArrTimeBlk,DistanceGroup,DivAirportLandings,DepTime2
0,2020-07-17,American Airlines Inc.,MSN,DFW,False,False,700,2350.0,3890.0,3890.0,146.0,3864.0,101.0,142.0,116.0,821.0,2020,3,7,17,5,AA,AA,19805,AA,2884,AA,19805,AA,N818AW,2884,13485,1348502,33485,"Madison, WI",WI,55,Wisconsin,45,11298,1129806,30194,"Dallas/Fort Worth, TX",TX,48,Texas,74,1.0,12.0,0700-0759,10.0,2400.0,141.0,5.0,922,3864.0,1.0,12.0,0900-0959,4,0.0,39.166667
1,2020-12-10,American Airlines Inc.,STT,MIA,False,False,819,1131.0,3072.0,3072.0,1324.0,3069.0,153.0,176.0,173.0,1107.0,2020,4,12,10,4,AA,AA,19805,AA,230,AA,19805,AA,N983AN,230,15024,1502403,34945,"Charlotte Amalie, VI",VI,78,U.S. Virgin Islands,4,13303,1330303,32467,"Miami, FL",FL,12,Florida,33,1.0,12.0,0800-0859,13.0,1144.0,1317.0,7.0,1015,3069.0,1.0,12.0,1000-1059,5,0.0,18.850000
2,2020-02-19,American Airlines Inc.,STT,CLT,False,False,1749,1643.0,2814.0,2814.0,1926.0,2794.0,206.0,243.0,223.0,1520.0,2020,1,2,19,3,AA,AA,19805,AA,1195,AA,19805,AA,N187AN,1195,15024,1502403,34945,"Charlotte Amalie, VI",VI,78,U.S. Virgin Islands,4,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,1.0,12.0,1700-1759,12.0,1655.0,1921.0,5.0,2052,2794.0,1.0,12.0,2000-2059,7,0.0,27.383333
3,2020-12-04,American Airlines Inc.,HNL,ORD,False,False,1825,1227.0,2522.0,2522.0,109.0,2568.0,492.0,476.0,522.0,4243.0,2020,4,12,4,5,AA,AA,19805,AA,74,AA,19805,AA,N751AN,74,12173,1217305,32134,"Honolulu, HI",HI,15,Hawaii,2,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,1.0,12.0,1800-1859,21.0,1248.0,100.0,9.0,621,2568.0,1.0,12.0,0600-0659,11,0.0,20.450000
4,2020-03-13,Endeavor Air Inc.,CLT,LGA,False,False,1608,1107.0,2579.0,2579.0,1255.0,2560.0,74.0,127.0,108.0,544.0,2020,1,3,13,5,DL,DL_CODESHARE,19790,DL,5363,9E,20363,9E,N906XJ,5363,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,12953,1295304,31703,"New York, NY",NY,36,New York,22,1.0,12.0,1600-1659,22.0,1129.0,1243.0,12.0,1815,2560.0,1.0,12.0,1800-1859,3,0.0,18.450000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5022392,2020-04-01,Republic Airlines,DEN,DRO,True,False,2010,NaN,NaN,NaN,NaN,NaN,NaN,74.0,NaN,251.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3419,YX,20452,YX,N751YX,3419,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,11413,1141307,30285,"Durango, CO",CO,8,Colorado,82,NaN,NaN,2000-2059,NaN,NaN,NaN,NaN,2124,NaN,NaN,NaN,2100-2159,2,0.0,NaN
5022393,2020-04-01,Republic Airlines,DEN,CLT,True,False,955,NaN,NaN,NaN,NaN,NaN,NaN,202.0,NaN,1337.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3418,YX,20452,YX,N648RW,3418,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,NaN,NaN,0900-0959,NaN,NaN,NaN,NaN,1517,NaN,NaN,NaN,1500-1559,6,0.0,NaN
5022394,2020-04-01,Republic Airlines,IND,ORD,True,False,845,NaN,NaN,NaN,NaN,NaN,NaN,71.0,NaN,177.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3417,YX,20452,YX,N749YX,3417,12339,1233904,32337,"Indianapolis, IN",IN,18,Indiana,42,13930,1393007,30977,"Chicago, IL",IL,17,Illinois,41,NaN,NaN,0800-0859,NaN,NaN,NaN,NaN,856,NaN,NaN,NaN,0800-0859,1,0.0,NaN
5022395,2020-04-01,Republic Airlines,CMH,IAH,True,False,830,NaN,NaN,NaN,NaN,NaN,NaN,193.0,NaN,986.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3412,YX,20452,YX,N862RW,3412,11066,1106606,31066,"Columbus, OH",OH,39,Ohio,44,12266,1226603,31453,"Houston, TX",TX,48,Texas,74,NaN,NaN,0800-0859,NaN,NaN,NaN,NaN,1043,NaN,NaN,NaN,1000-1059,4,0.0,NaN
5022396,2020-04-01,Republic Airlines,CLT,DEN,True,False,1645,NaN,NaN,NaN,NaN,NaN,NaN,235.0,NaN,1337.0,2020,2,4,1,3,UA,UA_CODESHARE,19977,UA,3404,YX,20452,YX,N648RW,3404,11057,1105703,31057,"Charlotte, NC",NC,37,North Carolina,36,11292,1129202,30325,"Denver, CO",CO,8,Colorado,82,NaN,NaN,1600-1659,NaN,NaN,NaN,NaN,1840,NaN,NaN,NaN,1800-1859,6,0.0,NaN

In [190]:
df[['FlightDate', 'Airline', 'ArrDelay']].sort_index()

       FlightDate                 Airline  ArrDelay
0      2020-09-01             Comair Inc.     -22.0
0      2020-01-17         JetBlue Airways     -11.0
0      2020-02-01               Envoy Air      -8.0
0      2020-07-22  Southwest Airlines Co.     -23.0
0      2020-05-31  Southwest Airlines Co.      -9.0
...           ...                     ...       ...
701269 2020-03-06        Spirit Air Lines      -8.0
701270 2020-03-07        Spirit Air Lines     -12.0
701271 2020-03-08        Spirit Air Lines       5.0
701272 2020-03-09        Spirit Air Lines       0.0
701273 2020-03-10        Spirit Air Lines     160.0

[5022397 rows x 3 columns]

# Handling Missing Data

In [191]:
df[['FlightDate', 'Airline', 'ArrDelay']].isna() # returns boolean for each valuie in df if missing

        FlightDate  Airline  ArrDelay
0            False    False     False
1            False    False     False
2            False    False     False
3            False    False     False
4            False    False     False
...            ...      ...       ...
331233       False    False      True
331234       False    False     False
331235       False    False     False
331236       False    False     False
331237       False    False     False

[5022397 rows x 3 columns]

In [192]:
df[['FlightDate', 'Airline', 'ArrDelay']].isna().sum() # count of missing values

FlightDate         0
Airline            0
ArrDelay      309467
dtype: int64

In [193]:
df[['FlightDate', 'Airline', 'ArrDelay']].dropna() # drop NaN

       FlightDate            Airline  ArrDelay
0      2020-09-01        Comair Inc.     -22.0
1      2020-09-02        Comair Inc.     -29.0
2      2020-09-03        Comair Inc.      26.0
3      2020-09-04        Comair Inc.     -29.0
4      2020-09-05        Comair Inc.     -30.0
...           ...                ...       ...
331232 2020-04-01  Republic Airlines      -6.0
331234 2020-04-01  Republic Airlines     -35.0
331235 2020-04-01  Republic Airlines     132.0
331236 2020-04-01  Republic Airlines     -17.0
331237 2020-04-01  Republic Airlines     -27.0

[4712930 rows x 3 columns]

In [194]:
df[['FlightDate', 'Airline', 'ArrDelay']].dropna(subset=['ArrDelay']) # Only drop null in specified column

       FlightDate            Airline  ArrDelay
0      2020-09-01        Comair Inc.     -22.0
1      2020-09-02        Comair Inc.     -29.0
2      2020-09-03        Comair Inc.      26.0
3      2020-09-04        Comair Inc.     -29.0
4      2020-09-05        Comair Inc.     -30.0
...           ...                ...       ...
331232 2020-04-01  Republic Airlines      -6.0
331234 2020-04-01  Republic Airlines     -35.0
331235 2020-04-01  Republic Airlines     132.0
331236 2020-04-01  Republic Airlines     -17.0
331237 2020-04-01  Republic Airlines     -27.0

[4712930 rows x 3 columns]

In [195]:
df[['FlightDate', 'Airline', 'ArrDelay']].fillna(999) # fills nulls with specified values

       FlightDate            Airline  ArrDelay
0      2020-09-01        Comair Inc.     -22.0
1      2020-09-02        Comair Inc.     -29.0
2      2020-09-03        Comair Inc.      26.0
3      2020-09-04        Comair Inc.     -29.0
4      2020-09-05        Comair Inc.     -30.0
...           ...                ...       ...
331233 2020-04-01  Republic Airlines     999.0
331234 2020-04-01  Republic Airlines     -35.0
331235 2020-04-01  Republic Airlines     132.0
331236 2020-04-01  Republic Airlines     -17.0
331237 2020-04-01  Republic Airlines     -27.0

[5022397 rows x 3 columns]

In [196]:
df['ArrDelay'].fillna(df['ArrDelay'].mean()) # fill na w/ summerizing methods

0         -22.000000
1         -29.000000
2          26.000000
3         -29.000000
4         -30.000000
             ...
331233     -4.863644
331234    -35.000000
331235    132.000000
331236    -17.000000
331237    -27.000000
Name: ArrDelay, Length: 5022397, dtype: float64

# Combining Data

In [197]:
df['Airline'].value_counts()

Airline
Southwest Airlines Co.                       961276
SkyWest Airlines Inc.                        596986
Delta Air Lines Inc.                         581101
American Airlines Inc.                       569806
United Air Lines Inc.                        308217
Republic Airlines                            219772
Endeavor Air Inc.                            211457
Envoy Air                                    211435
Comair Inc.                                  192613
JetBlue Airways                              144163
Alaska Airlines Inc.                         138226
Mesa Airlines Inc.                           135927
Spirit Air Lines                             135102
Allegiant Air                                 98489
Horizon Air                                   96063
Frontier Airlines Inc.                        91175
Capital Cargo International                   72359
Air Wisconsin Airlines Corp                   53989
ExpressJet Airlines Inc.                      52212
Hawaiian Airlines Inc.                        40414
GoJet Airlines, LLC d/b/a United Express      38989
Commutair Aka Champlain Enterprises, Inc.     32953
Trans States Airlines                         18705
Compass Airlines                              15878
Empire Airlines Inc.                           5090
Name: count, dtype: int64

In [198]:
df1 = df.query('Airline == "Southwest Airlines Co."').copy()
df2 = df.query('Airline == "Delta Air Lines Inc."').copy()

In [199]:
df_stack = pd.concat([df1,df2]) # stack df's ontop of eachother, same # of columns but combined rows

In [200]:
df1 = df1.reset_index(drop=True)
df2 = df2.reset_index(drop=True)
df_side = pd.concat([df1,df2], axis=1) # merged on the similar indexes, same rows as largest dataset and doubled the columns

In [201]:
df1.shape, df2.shape, df_stack.shape, df_side.shape

((961276, 62), (581101, 62), (1542377, 62), (961276, 124))

In [202]:
df_side[['FlightDate']] # Concat can cause problem of multiple columns w/ same name

       FlightDate FlightDate
0      2020-09-03 2020-09-01
1      2020-09-03 2020-09-01
2      2020-09-03 2020-09-01
3      2020-09-03 2020-09-01
4      2020-09-03 2020-09-01
...           ...        ...
961271 2020-04-30        NaT
961272 2020-04-30        NaT
961273 2020-04-30        NaT
961274 2020-04-30        NaT
961275 2020-04-30        NaT

[961276 rows x 2 columns]

# Merge Data

In [203]:
df1 = df.groupby(['Airline', 'FlightDate'])[['DepDelay']].mean().reset_index()
df2 = df.groupby(['Airline', 'FlightDate'])[['ArrDelay']].mean().reset_index()

In [204]:
df1.merge(df2) # Combines similar columns so there are not dupe columns

                          Airline FlightDate  DepDelay   ArrDelay
0     Air Wisconsin Airlines Corp 2020-01-01  4.561702  -7.740426
1     Air Wisconsin Airlines Corp 2020-01-02 -0.833898 -11.454237
2     Air Wisconsin Airlines Corp 2020-01-03  0.932203  -8.204082
3     Air Wisconsin Airlines Corp 2020-01-04  7.716216   3.195946
4     Air Wisconsin Airlines Corp 2020-01-05  2.920530  -7.158940
...                           ...        ...       ...        ...
8505        United Air Lines Inc. 2020-12-27  5.419187  -1.716823
8506        United Air Lines Inc. 2020-12-28  3.930185   0.832990
8507        United Air Lines Inc. 2020-12-29  4.338477  -0.439175
8508        United Air Lines Inc. 2020-12-30  5.908624   1.257965
8509        United Air Lines Inc. 2020-12-31  1.816352  -5.206549

[8510 rows x 4 columns]

In [205]:
df1.merge(df2, how='left') # how='inner' is default

                          Airline FlightDate  DepDelay   ArrDelay
0     Air Wisconsin Airlines Corp 2020-01-01  4.561702  -7.740426
1     Air Wisconsin Airlines Corp 2020-01-02 -0.833898 -11.454237
2     Air Wisconsin Airlines Corp 2020-01-03  0.932203  -8.204082
3     Air Wisconsin Airlines Corp 2020-01-04  7.716216   3.195946
4     Air Wisconsin Airlines Corp 2020-01-05  2.920530  -7.158940
...                           ...        ...       ...        ...
8505        United Air Lines Inc. 2020-12-27  5.419187  -1.716823
8506        United Air Lines Inc. 2020-12-28  3.930185   0.832990
8507        United Air Lines Inc. 2020-12-29  4.338477  -0.439175
8508        United Air Lines Inc. 2020-12-30  5.908624   1.257965
8509        United Air Lines Inc. 2020-12-31  1.816352  -5.206549

[8510 rows x 4 columns]

In [206]:
# another way to merge

In [207]:
pd.merge(df1, df2, on=['Airline']) # Can merge on specific columns
# other columns will have suffix x or y

,Airline,FlightDate_x,DepDelay,FlightDate_y,ArrDelay
0,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-01,-7.740426
1,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-02,-11.454237
2,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-03,-8.204082
3,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-04,3.195946
4,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-05,-7.158940
...,...,...,...,...,...
3036341,United Air Lines Inc.,2020-12-31,1.816352,2020-12-27,-1.716823
3036342,United Air Lines Inc.,2020-12-31,1.816352,2020-12-28,0.832990
3036343,United Air Lines Inc.,2020-12-31,1.816352,2020-12-29,-0.439175
3036344,United Air Lines Inc.,2020-12-31,1.816352,2020-12-30,1.257965
3036345,United Air Lines Inc.,2020-12-31,1.816352,2020-12-31,-5.206549

In [208]:
pd.merge(df1, df2, on=['Airline'], suffixes=('_dep','_arr'))
# can change suffix like this

,Airline,FlightDate_dep,DepDelay,FlightDate_arr,ArrDelay
0,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-01,-7.740426
1,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-02,-11.454237
2,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-03,-8.204082
3,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-04,3.195946
4,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-05,-7.158940
...,...,...,...,...,...
3036341,United Air Lines Inc.,2020-12-31,1.816352,2020-12-27,-1.716823
3036342,United Air Lines Inc.,2020-12-31,1.816352,2020-12-28,0.832990
3036343,United Air Lines Inc.,2020-12-31,1.816352,2020-12-29,-0.439175
3036344,United Air Lines Inc.,2020-12-31,1.816352,2020-12-30,1.257965
3036345,United Air Lines Inc.,2020-12-31,1.816352,2020-12-31,-5.206549

In [209]:
pd.merge(df1, df2, left_on=['Airline'], right_on=['Airline'], suffixes=('_dep','_arr'))
# if dataframes have different columns

,Airline,FlightDate_dep,DepDelay,FlightDate_arr,ArrDelay
0,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-01,-7.740426
1,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-02,-11.454237
2,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-03,-8.204082
3,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-04,3.195946
4,Air Wisconsin Airlines Corp,2020-01-01,4.561702,2020-01-05,-7.158940
...,...,...,...,...,...
3036341,United Air Lines Inc.,2020-12-31,1.816352,2020-12-27,-1.716823
3036342,United Air Lines Inc.,2020-12-31,1.816352,2020-12-28,0.832990
3036343,United Air Lines Inc.,2020-12-31,1.816352,2020-12-29,-0.439175
3036344,United Air Lines Inc.,2020-12-31,1.816352,2020-12-30,1.257965
3036345,United Air Lines Inc.,2020-12-31,1.816352,2020-12-31,-5.206549